-- Enable Row Level Security (RLS) on all public tables to prevent unauthorized direct REST API access.

ALTER TABLE "Task" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OpsUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Healthmate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Participant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OpsMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
